/* Generated by Cython 0.29.14 */

#ifndef __PYX_HAVE__agilent_u2541a_wrapped
#define __PYX_HAVE__agilent_u2541a_wrapped

#include <python2.7/Python.h>

#ifndef __PYX_HAVE_API__agilent_u2541a_wrapped

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *create_usbtmc_agilent(char const *);
__PYX_EXTERN_C char *check_identity(PyObject *);
__PYX_EXTERN_C void send_msg(PyObject *, char const *);
__PYX_EXTERN_C char *ask(PyObject *, char const *);
__PYX_EXTERN_C void reset_device(PyObject *);
__PYX_EXTERN_C void wait_for_data(PyObject *);
__PYX_EXTERN_C char *read_raw(PyObject *);
__PYX_EXTERN_C char *one_sample(PyObject *);

#endif /* !__PYX_HAVE_API__agilent_u2541a_wrapped */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initagilent_u2541a_wrapped(void);
#else
PyMODINIT_FUNC PyInit_agilent_u2541a_wrapped(void);
#endif

#endif /* !__PYX_HAVE__agilent_u2541a_wrapped */
