/* Generated by Cython 0.29.14 */

#ifndef __PYX_HAVE__usbtmc_standard_interface_python
#define __PYX_HAVE__usbtmc_standard_interface_python

#include <python2.7/Python.h>

#ifndef __PYX_HAVE_API__usbtmc_standard_interface_python

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C char *check_available_devices(void);
__PYX_EXTERN_C void set_data_size(PyObject *, char const *);
__PYX_EXTERN_C int last_data_size(PyObject *);
__PYX_EXTERN_C PyObject *create_usbtmc_agilent(char const *);
__PYX_EXTERN_C char *check_identity(PyObject *);
__PYX_EXTERN_C void send_msg(PyObject *, char const *);
__PYX_EXTERN_C char *ask(PyObject *, char const *);
__PYX_EXTERN_C void reset_device(PyObject *);
__PYX_EXTERN_C void wait_for_data(PyObject *);
__PYX_EXTERN_C char *read_raw(PyObject *);
__PYX_EXTERN_C char *one_sample(PyObject *);

#endif /* !__PYX_HAVE_API__usbtmc_standard_interface_python */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initusbtmc_standard_interface_python(void);
#else
PyMODINIT_FUNC PyInit_usbtmc_standard_interface_python(void);
#endif

#endif /* !__PYX_HAVE__usbtmc_standard_interface_python */
